In [2]:
%matplotlib notebook

In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [6]:
census = "Resources/society_redistricting_2010.gpkg"
school_areas = "Resources/bdry_school_attendance_areas.gpkg"

census_block_df = gpd.read_file(census)
school_area_df = gpd.read_file(school_areas)

In [13]:
census_block_df.describe()

,ID,AREA,COLORING,POP2000,POPULATION,HISPANIC_O,NH_WHT,NH_DOJ_BLK,NH_DOJ_IND,NH_DOJ_ASN,...,AUDR10,AUDDFL10,AUDGP10,AUDGR10,AUDWI10,AGIP10,AGR10,AGDFL10,AGTRP10,AGWI10
count,2.597770e+05,259777.000000,259777.000000,259777.000000,259777.000000,259777.000000,259777.000000,259777.000000,259777.000000,259777.000000,...,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000,259526.000000
mean,1.847257e+07,0.333804,1.682320,18.937358,20.417223,0.963357,16.957398,1.168879,0.308299,0.910727,...,3.692173,3.787347,0.209216,0.137320,0.004724,0.397255,3.239556,4.149029,0.054226,0.006234
std,1.083804e+07,2.389127,1.316708,49.700248,54.359624,6.510233,42.651849,11.347672,2.888832,6.159455,...,9.965202,10.133587,0.580230,0.332671,0.027439,0.972256,8.945200,10.958454,0.150942,0.030013
min,3.492890e+05,0.000001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.845958e+06,0.004705,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.816591e+07,0.016245,2.000000,3.000000,3.000000,0.000000,3.000000,0.000000,0.000000,0.000000,...,0.693074,0.553314,0.024639,0.024793,0.000000,0.076775,0.583942,0.634921,0.000000,0.000000
75%,2.622100e+07,0.229390,3.000000,18.000000,19.000000,0.000000,17.000000,0.000000,0.000000,0.000000,...,3.503411,3.300398,0.187930,0.153061,0.000000,0.429121,2.983607,3.695807,0.054010,0.000000
max,4.146115e+07,695.509636,10.000000,3242.000000,3043.000000,627.000000,2446.000000,2643.000000,435.000000,579.000000,...,328.553223,437.441864,42.000000,24.619724,5.450550,49.000000,302.676697,437.441864,11.815459,5.000000

In [9]:
census_block_df = census_block_df.to_crs({'init': 'epsg:26915'})
school_area_df = school_area_df.to_crs({'init': 'epsg:26915'})

In [10]:
census_school_intersect = gpd.sjoin(census_block_df, school_area_df, how="inner", op='intersects')

In [14]:
census_df.head()

,ID,AREA,COLORING,BLOCK,BLOCKGROUP,TRACT,COUNTY,STATE,BLOCK2000,MCD,...,AGIP10,AGR10,AGDFL10,AGTRP10,AGWI10,DEM_INDEX,REP_INDEX,THIRD_INDE,INDEX_VOTE,geometry
0,38861169.0,28.797564,2,271370114002121,271370114002,27137011400,27137,27,271370114002036,2713770069,...,0.0,0.0,0.0,0.0,0.0,None,None,None,None,"POLYGON ((563689.2199367753 5253232.147392472,..."
1,38861200.0,0.331563,4,271370114002236,271370114002,27137011400,27137,27,271370114002242,2713770069,...,0.0,0.0,0.0,0.0,0.0,None,None,None,None,"POLYGON ((570103.4706400972 5241579.915064286,..."
2,38861216.0,1.500685,2,271370114002116,271370114002,27137011400,27137,27,271370114002073,2713770069,...,0.0,0.0,0.0,0.0,0.0,None,None,None,None,"POLYGON ((571927.5697937486 5242048.729431494,..."
3,38861236.0,0.615580,0,271370114002152,271370114002,27137011400,27137,27,271370114002071,2713770069,...,0.0,0.0,0.0,0.0,0.0,None,None,None,None,"POLYGON ((569458.6838608072 5244689.955503405,..."
4,38861256.0,0.101863,2,271370114002153,271370114002,27137011400,27137,27,271370114002072,2713770069,...,0.0,0.0,0.0,0.0,0.0,None,None,None,None,"POLYGON ((570573.6117597707 5245656.542985615,..."

In [28]:

list(census_school_intersect.columns)

['ID',
 'AREA',
 'COLORING',
 'BLOCK',
 'BLOCKGROUP',
 'TRACT',
 'COUNTY',
 'STATE',
 'BLOCK2000',
 'MCD',
 'SUBMCD',
 'PLACE',
 'CONCITY',
 'VTD',
 'CONGRESS',
 'LOWERSLD',
 'UPPERSLD',
 'COUNTYLD',
 'CITYLD',
 'INDIAN',
 'TRUST',
 'TRIBALSUB',
 'ANRC',
 'CSA',
 'CBSA',
 'CBSADIV',
 'UA',
 'UGA',
 'ELEMSCHOOL',
 'SECSCHOOL',
 'UNIFSCHOOL',
 'ZIP5',
 'URBANRURAL',
 'POP2000',
 'POPULATION',
 'HISPANIC_O',
 'NH_WHT',
 'NH_DOJ_BLK',
 'NH_DOJ_IND',
 'NH_DOJ_ASN',
 'NH_DOJ_HWN',
 'NH_DOJ_OTH',
 'NH_DOJ_OT1',
 'F18_POP_20',
 'F18_POP',
 'H18_POP',
 'NH18_WHT',
 'NH18_DOJ_B',
 'NH18_DOJ_I',
 'NH18_DOJ_A',
 'NH18_DOJ_H',
 'NH18_DOJ_O',
 'NH18_DOJ_1',
 'SLIVER',
 'USSENGP02',
 'USSENIP02',
 'USSENR02',
 'WELLSTONE',
 'USSENDFL02',
 'USSENCP02',
 'USSENWI02',
 'CONGGP02',
 'CONGIP02',
 'CONGR02',
 'CONGDFL02',
 'CONGNNT02',
 'CONGWI02',
 'MNSENGP02',
 'MNSENIP02',
 'MNSENR02',
 'MNSENDFL02',
 'MNSENCP02',
 'MNSENICP02',
 'MNSENWI02',
 'MNLEGGP02',
 'MNLEGIP02',
 'MNLEGR02',
 'MNLEGDFL02',
 'MNLEGCP02',
 'MNLEGGI02',
 'MNLEGWI02',
 'GOVGP02',
 'GOVIP02',
 'GOVR02',
 'GOVDFL02',
 'GOVCP02',
 'GOVI02',
 'GOVSW02',
 'GOVWI02',
 'SOSGP02',
 'SOSIP02',
 'SOSR02',
 'SOSDFL02',
 'SOSWI02',
 'AGIP02',
 'AGR02',
 'AGDFL02',
 'AGWI02',
 'AUDGP02',
 'AUDIP02',
 'AUDR02',
 'AUDDFL02',
 'AUDWI02',
 'USPRESGP04',
 'USPRESR04',
 'USPRESDFL0',
 'USPRESSE04',
 'USPRESSW04',
 'USPRESCF04',
 'USPRESBL04',
 'USPRESC04',
 'USPRESL04',
 'USPRESWI04',
 'USCONGI04',
 'USCONGR04',
 'USCONGDFL0',
 'USCONGWI04',
 'MNLEGI04',
 'MNLEGR04',
 'MNLEGDFL04',
 'MNLEGWI04',
 'USSENR06',
 'USSENDFL06',
 'USSENIP06',
 'USSENWI06',
 'GOVR06',
 'GOVDFL06',
 'GOVIP06',
 'GOVWI06',
 'AGR06',
 'AGDFL06',
 'AGIP06',
 'AGWI06',
 'SOSR06',
 'SOSDFL06',
 'SOSIP06',
 'SOSWI06',
 'AUDR06',
 'AUDDFL06',
 'AUDWI06',
 'CONGR06',
 'CONGDFL06',
 'CONGIP06',
 'CONGWI06',
 'MNSENR06',
 'MNSENDFL06',
 'MNSENIP06',
 'MNSENWI06',
 'MNLEGR06',
 'MNLEGDFL06',
 'MNLEGIP06',
 'MNLEGWI06',
 'USPRESR08',
 'USPRESDFL1',
 'USPRESGP08',
 'USPRESSWP0',
 'USPRESIND0',
 'USPRESLIB0',
 'USPRESCP08',
 'USPRESWI08',
 'USSENIP08',
 'USSENR08',
 'USSENDFL08',
 'USSENLIB08',
 'USSENCP08',
 'USSENWI08',
 'CONGIP08',
 'CONGR08',
 'CONGDFL08',
 'CONGWI08',
 'MNLEGIP08',
 'MNLEGR08',
 'MNLEGDFL08',
 'MNLEGWI08',
 'CONGIP10',
 'CONGR10',
 'CONGDFL10',
 'CONGWI10',
 'MNSENIP10',
 'MNSENR10',
 'MNSENDFL10',
 'MNSENWI10',
 'MNLEGIP10',
 'MNLEGR10',
 'MNLEGDFL10',
 'MNLEGWI10',
 'GOVIP10',
 'GOVR10',
 'GOVDFL10',
 'GOVGP10',
 'GOVTRP10',
 'GOVGR10',
 'GOVEDP10',
 'GOVWI10',
 'SOSIP10',
 'SOSR10',
 'SOSDFL10',
 'SOSWI10',
 'AUDR10',
 'AUDDFL10',
 'AUDGP10',
 'AUDGR10',
 'AUDWI10',
 'AGIP10',
 'AGR10',
 'AGDFL10',
 'AGTRP10',
 'AGWI10',
 'DEM_INDEX',
 'REP_INDEX',
 'THIRD_INDE',
 'INDEX_VOTE',
 'geometry',
 'index_right',
 'Shape_Leng',
 'Shape_Area',
 'UNI_TYP',
 'UNI_MAJ',
 'UNI_NAM',
 'ELEM_NAME',
 'MIDD_NAME',
 'HIGH_NAME']

In [24]:
#plt.savefig('census.png')

In [31]:
census_subset=census_school_intersect[['STATE', 'BLOCKGROUP', 'BLOCK', 'TRACT', 'MCD', 'SUBMCD', 'PLACE',  'UNI_NAM', 'HIGH_NAME', 'MIDD_NAME', 'ELEM_NAME', 'URBANRURAL', 'POPULATION']]

In [32]:
census_school_intersect.head()

,ID,AREA,COLORING,BLOCK,BLOCKGROUP,TRACT,COUNTY,STATE,BLOCK2000,MCD,...,geometry,index_right,Shape_Leng,Shape_Area,UNI_TYP,UNI_MAJ,UNI_NAM,ELEM_NAME,MIDD_NAME,HIGH_NAME
0,38861169.0,28.797564,2,271370114002121,271370114002,27137011400,27137,27,271370114002036,2713770069,...,"POLYGON ((563689.2199367753 5253232.147392472,...",751,144441.273885,1.031479e+09,01,2711,Mesabi East,MESABI EAST,None,MESABI EAST
1,38861200.0,0.331563,4,271370114002236,271370114002,27137011400,27137,27,271370114002242,2713770069,...,"POLYGON ((570103.4706400972 5241579.915064286,...",751,144441.273885,1.031479e+09,01,2711,Mesabi East,MESABI EAST,None,MESABI EAST
2,38861216.0,1.500685,2,271370114002116,271370114002,27137011400,27137,27,271370114002073,2713770069,...,"POLYGON ((571927.5697937486 5242048.729431494,...",751,144441.273885,1.031479e+09,01,2711,Mesabi East,MESABI EAST,None,MESABI EAST
3,38861236.0,0.615580,0,271370114002152,271370114002,27137011400,27137,27,271370114002071,2713770069,...,"POLYGON ((569458.6838608072 5244689.955503405,...",751,144441.273885,1.031479e+09,01,2711,Mesabi East,MESABI EAST,None,MESABI EAST
4,38861256.0,0.101863,2,271370114002153,271370114002,27137011400,27137,27,271370114002072,2713770069,...,"POLYGON ((570573.6117597707 5245656.542985615,...",751,144441.273885,1.031479e+09,01,2711,Mesabi East,MESABI EAST,None,MESABI EAST

In [25]:
census_block_df.to_csv('Resources/census_subset.csv')

In [20]:
check_path = "Resources/census_subset.csv"
check = pd.read_csv(check_path)

In [21]:
check

,Unnamed: 0,STATE,BLOCKGROUP,BLOCK,TRACT,MCD,SUBMCD,PLACE,SECSCHOOL,ELEMSCHOOL,ZIP5,URBANRURAL,POPULATION
0,0,27,271370114002,271370114002121,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,27,271370114002,271370114002236,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2,27,271370114002,271370114002116,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3,27,271370114002,271370114002152,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,27,271370114002,271370114002153,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
5,5,27,271370114002,271370114002132,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
6,6,27,271370114002,271370114002148,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
7,7,27,271370114002,271370114002150,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
8,8,27,271370114002,271370114002149,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
9,9,27,271370114002,271370114002154,27137011400,2713770069,NaN,NaN,NaN,NaN,NaN,NaN,0
10,10,27,271370114002,271370114002151,27137011400,2713720186,NaN,NaN,NaN,NaN,NaN,NaN,0
11,11,27,271370114002,271370114002117,27137011400,2713720186,NaN,NaN,NaN,NaN,NaN,NaN,0
12,12,27,271370114002,271370114002118,27137011400,2713703880,NaN,NaN,NaN,NaN,NaN,NaN,0
13,13,27,271370114002,271370114002120,27137011400,2713703880,NaN,NaN,NaN,NaN,NaN,NaN,0
14,14,27,271370114002,271370114002119,27137011400,2713703880,NaN,NaN,NaN,NaN,NaN,NaN,0
15,15,27,271370114002,271370114002358,27137011400,2713703880,NaN,NaN,NaN,NaN,NaN,NaN,0
16,16,27,271370114002,271370114002348,27137011400,2713703880,NaN,NaN,NaN,NaN,NaN,NaN,0
17,17,27,271370139002,271370139002150,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,87
18,18,27,271370139002,271370139002151,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,0
19,19,27,271370139002,271370139002167,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,0
20,20,27,271370139002,271370139002158,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,0
21,21,27,271370139002,271370139002130,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,9
22,22,27,271370139002,271370139002136,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,0
23,23,27,271370139002,271370139002149,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,2
24,24,27,271370139002,271370139002135,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,13
25,25,27,271370139002,271370139002134,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,12
26,26,27,271370139002,271370139002125,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,7
27,27,27,271370139002,271370139002127,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,9
28,28,27,271370139002,271370139002126,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,7
29,29,27,271370139002,271370139002124,27137013900,2713769898,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259747,259747,27,270314801002,270314801002389,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,3
259748,259748,27,270314801002,270314801002388,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259749,259749,27,270314801002,270314801002386,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259750,259750,27,270314801002,270314801002387,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,1
259751,259751,27,270314801002,270314801002378,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,56
259752,259752,27,270314801002,270314801002379,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,12
259753,259753,27,270319900000,270319900000011,27031990000,2703135172,NaN,NaN,NaN,NaN,NaN,NaN,0
259754,259754,27,270319900000,270319900000003,27031990000,2703135172,NaN,NaN,NaN,NaN,NaN,NaN,0
259755,259755,27,270314801002,270314801002405,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,9
259756,259756,27,270314801002,270314801002307,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,2
259757,259757,27,270314801002,270314801002310,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259758,259758,27,270314801002,270314801002308,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,2
259759,259759,27,270314801002,270314801002393,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259760,259760,27,270314801002,270314801002392,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259761,259761,27,270314801002,270314801002317,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,4
259762,259762,27,270314801002,270314801002311,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,3
259763,259763,27,270314801002,270314801002321,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,1
259764,259764,27,270314801002,270314801002404,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,4
259765,259765,27,270314801002,270314801002318,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,32
259766,259766,27,270314801002,270314801002320,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,6
259767,259767,27,270314801002,270314801002322,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,7
259768,259768,27,270314801002,270314801002373,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259769,259769,27,270314801002,270314801002369,27031480100,2703117531,NaN,NaN,NaN,NaN,NaN,NaN,0
259770,259770,27,270314801002,270314801002003,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259771,259771,27,270314801002,270314801002005,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259772,259772,27,270314801002,270314801002008,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259773,259773,27,270314801002,270314801002004,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259774,259774,27,270314801002,270314801002002,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259775,259775,27,270314801002,270314801002001,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0
259776,259776,27,270314801002,270314801002000,27031480100,2703125071,NaN,NaN,NaN,NaN,NaN,NaN,0